package leetcode.easy;

// Leetcode Problem N389
// Related Topic: Hashtable, String, Bit Manipulation, Sorting
//        You are given two strings s and t.
//        String t is generated by random shuffling string s and then add one more letter at a random position.
//        Return the letter that was added to t.
public class FindTheDifference {
    public static void main(String[] args) {
        Solution solution = new Solution();
        String s = "";
        String t = "h";

        System.out.println(solution.findTheDifference(s, t));
    }

    // Bit Manipulation approach
    static class Solution {
        public char findTheDifference(String s, String t) {
            char[] sArr = s.toCharArray();
            char[] tArr = t.toCharArray();

            char res = 0;
            for (char c : sArr) {
                res ^= c;
            }
            for (char c : tArr) {
                res ^= c;
            }
            return res;
        }
    }
}
